server:
  port: 8080
spring:
  application:
    name: products
  datasource:
    url: jdbc:h2:file:~/products;AUTO_SERVER=true
    username: root
    password: admin123
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
