server:
  port: 8080
spring:
  application:
    name: products
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}